package com.example.transport

import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.launch
import java.io.OutputStream
import java.net.InetSocketAddress
import java.net.Socket
import java.util.concurrent.atomic.AtomicLong

class TcpAudioSender {

    private var socket: Socket? = null
    private var outputStream: OutputStream? = null

    val pcmChunks = AtomicLong(0)
    val pcmBytesSent = AtomicLong(0)

    @Volatile
    var isConnected: Boolean = false
        private set

    var onLog: ((String) -> Unit)? = null

    private val scope = CoroutineScope(Dispatchers.IO + SupervisorJob())

    @Synchronized
    fun start(pcIp: String, tcpPort: Int) {
        stop()
        pcmChunks.set(0)
        pcmBytesSent.set(0)
        isConnected = false

        onLog?.invoke("TCP MIC TEST: connecting to $pcIp:$tcpPort")

        scope.launch {
            try {
                val newSocket = Socket()
                newSocket.connect(InetSocketAddress(pcIp, tcpPort), 3000)
                val os = newSocket.getOutputStream()

                synchronized(this@TcpAudioSender) {
                    socket = newSocket
                    outputStream = os
                    isConnected = true
                }
                onLog?.invoke("TCP MIC TEST: connected")
            } catch (e: Exception) {
                synchronized(this@TcpAudioSender) {
                    isConnected = false
                }
                onLog?.invoke("TCP MIC TEST: connection failed: ${e.localizedMessage ?: e.message}")
            }
        }
    }

    /**
     * For unit testing or injection of custom output streams.
     */
    @Synchronized
    fun startWithOutputStream(os: OutputStream) {
        stop()
        pcmChunks.set(0)
        pcmBytesSent.set(0)
        outputStream = os
        isConnected = true
        onLog?.invoke("TCP MIC TEST: connected (custom stream)")
    }

    /**
     * Sends raw PCM byte array sequentially over TCP socket.
     * Bytes sent are identical to outBytes generated by AudioRecorder.
     */
    fun sendPcmData(pcmData: ByteArray) {
        if (pcmData.isEmpty()) return

        val os = synchronized(this) {
            if (!isConnected) null else outputStream
        } ?: return

        try {
            synchronized(os) {
                os.write(pcmData)
                os.flush()
            }
            pcmChunks.incrementAndGet()
            pcmBytesSent.addAndGet(pcmData.size.toLong())
        } catch (e: Exception) {
            synchronized(this) {
                isConnected = false
            }
            onLog?.invoke("TCP MIC TEST: send error: ${e.localizedMessage ?: e.message}")
        }
    }

    fun logStats() {
        onLog?.invoke("TCP MIC TEST: pcm_chunks=${pcmChunks.get()}, pcm_bytes_sent=${pcmBytesSent.get()}, connection=${if (isConnected) "CONNECTED" else "DISCONNECTED"}")
    }

    @Synchronized
    fun stop() {
        if (!isConnected && outputStream == null && socket == null) {
            return
        }
        val connected = isConnected
        onLog?.invoke("TCP MIC TEST COMPLETE: pcm_chunks=${pcmChunks.get()}, pcm_bytes_sent=${pcmBytesSent.get()}, connection=${if (connected) "CONNECTED" else "DISCONNECTED"}")

        isConnected = false
        val os = outputStream
        val s = socket
        outputStream = null
        socket = null

        if (os != null) {
            try { os.close() } catch (e: Exception) { /* Ignore */ }
        }
        if (s != null && !s.isClosed) {
            try { s.close() } catch (e: Exception) { /* Ignore */ }
        }
    }
}
